on:
  pull_request:
    branches: [ master, develop, lambda ]

name: Deploy lambda

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install toolset
      run: dotnet tool install -g Amazon.Lambda.Tools
    - name: Deploy the function
      run: dotnet lambda deploy-function