on:
  pull_request:
    branches: [ master, develop ]

name: AWS Lambda Deployment

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install Lambda Tools
      run: dotnet tool install -g Amazon.Lambda.Tools
      
    - name: Deploy to Amazon Lambda
      working-directory: ./src/S3Lambda
      run: dotnet lambda deploy-function
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}